name: 构建二进制文件
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: windows-latest
        steps:
            - name: 检出仓库代码
              uses: actions/checkout@v4
            - name: 安装 uv
              uses: astral-sh/setup-uv@v5
              with:
                enable-cache: true
            - name: 设置 Python
              run: uv python install
            - name: 安装依赖
              run: |
                cd client
                uv sync
            - name: 构建二进制文件
              run: |
                cd client
                uv run build.py
